- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.ps1
Invoke-WebRequest does not handle utf-8 encoding. And the workaround is to use the .net System.Net.WebClient
> Fixed a problem with encoding of non-ascii characters in checkin comments

- Extensions/Versioning/VersionVSIXTask/ApplyVersionToVSIX.ps1
Make sure that $NewVersion is a string when set. Otherwise the following error might occur: 
```
System.Management.Automation.SetValueException: Cannot set "Version" because only strings can be used as values to set XmlNode properties.
```
> Make sure that $NewVersion is a string when set.

- Extensions/Versioning/VersionVSIXTask/ApplyVersionToVSIX.ps1
Set only the first two digits of the version as it is described in the comment of the task, but wasn't currently implemented. Took logic from PS version of the script.
> Set only the first two digits of the version.

- Extensions/Versioning/VersionNuspecTask/ApplyVersionToNuspec.ps1
Hi! First of all, thanks to the AWESOME plugin. Good work!
I found one minor issue when my Nuget description has special characters, even if the encoding is defined on the XML tag like this:
<?xml version="1.0" encoding="UTF-8"?>
So, if you force UTF-8 it via the Get-Content we would be on safe side.
> Force UTF-8 Encoding when reading the NuSpec

- Extensions/Versioning/VersionAssembliesTask/ApplyVersionToAssemblies.ps1
- Extensions/Versioning/VersionAssembliesTask/Get-FileEncoding.ps1
- Extensions/Versioning/VersionAssembliesTask/task.json
Related to #53, this will get the encoding of the file before it is modified and ensure it's written back with the same encoding.
> Writing back assemblyinfo.cs with same encoding

- Extensions/StyleCop/StyleCopTask/StyleCop.psm1
Fixes bug where the stylecop.settings file selected for the first
project in the folder structure would be used for subsequent projects.
> Fix stylecop.settings file selection

- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.ps1
- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/task.json
Added the ability to (optionally) set the markdown output to a variable.  This can be useful if you want to use the contents later on in your pipeline.
One issue I have is that all the documentation I have found for setting the variable requires the use of **Write-Host** which appears to remove the verbose logs when **system.debug** is set to true.
> Added variable as markdown output

- Extensions/BuildUpdating/BuildVariableTask/BuildVariableTask.ps1
Then got "(403) Forbidden"
Edit build definitions right sets crrectly
"Allow scripts to access OAuth token" marked on my environments
Helps me "UseDefaultCredentials" on webclient instead of Bearer token:
#$webclient.Headers.Add("Authorization" ,"Bearer $personalAccessToken") $webclient.UseDefaultCredentials = $true
> [FIX] Using UseDefaultCredentials instead of AccessToken

- Extensions/Pester/PesterTask/Pester.ps1
- Tests/Extensions/Pester/PesterTask/Pester.Tests.ps1
VSTS passes a string for it's tasks as it can't handle arrays correctly for parameters. 
This will now split that on commas and then strip single and double quotes. Tests have also been added to verify this.
> Tag and ExcludeTag not an array when passed from VSTS

- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.psm1
per the second bullet of my request #75
i see the complexity of skipping whole sections per your initial response to my first bullet, but still wondering if something like this would work for skipping individual items?
if that works - probably best to make optional via additional configuration boolean?
> skip commits with no description

- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.ps1
When I was trying to use the variable in an email task, all the line endings were removed.  This fixes it for me.  
I am worried this regresses #69, I can't replicate it, so I don't think it does.
> Fix for line endings issue when using variable

- Extensions/BuildUpdating/BuildVariableTask/BuildVariableTask.ps1
Information http://stackoverflow.com/questions/23552000/convertto-json-throws-error-when-using-a-string-terminating-in-backslash
> [FIX] The converted JSON string is in bad format

- Extensions/Versioning/VersionDacpacTask/Update-DacPacVersionNumber.ps1
- Extensions/Versioning/readme.md
As noted in #111, some dacpac references were being built but not versioned. It shouldn't try to version master or msdb as part of this task and this will fix that.
> Altered DacPac filter exlude master and msdb.

- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.ps1
- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.psm1
Fixed a bug with $defname and $stagename not populating in the template.
Added $releasedefname for the release definition name
> Fixed a bug with $defname and $stagename not populating in the template.

- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.ps1
- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.psm1
Since ```$releasedefid``` is unsupported for TFS 2015, I lookup the release definition id by the name. There is the risk that the release definition names could be the same across different release definition ids.
> Fix (Generate Release Notes): Undefined $releasedefid for TFS 2015

- Extensions/XplatGenerateReleaseNotes/XPlatGenerateReleaseNotesTask.src/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/XPlatGenerateReleaseNotesTask.src/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/XPlatGenerateReleaseNotesTask.src/agentSpecific.ts
Sorry about the large PR.  I'll try and document below.
**New Features**
- Added support for multiple artifacts.  Previously the plugin seemed to only deal with the primary build.  Work Items and commits are pulled in for all artifacts now.
**Fundamental Changes**
- I really struggled to add the multiple artifact support using the callback architecture.  I swapped it out for async/await.  
- Added a bunch more logging
- Converted code to be async/await compatible (eg. remove forEach)
**Fixes**
- TFVC changesets were not being pulled through because the changesets were prefixed with "C"
- TFVC changesets were being limited to 100.  I have changed this limit to 1000. 
- TFVC changeset comments were truncated.
- Line endings were not working correct when trying to use the output variable in …
> Added multiple artifact support + fixes a bunch of bugs

- Extensions/Versioning/VersionNuspecTask/ApplyVersionToNuspec.ps1
- Extensions/Versioning/VersionNuspecTask/task.json
- Extensions/Versioning/readme.md
- Tests/Extensions/Versioning/VersionNuspecTask/ApplyVersionToNuspec.Tests.ps1
Changed the Get-ChildItem filter so it looks in the root folder and everything under it for nuspec files rather than the previous method of finding all folders and then checking within those for nuspec files.
I've also added a bunch of tests but they probably need some more work.
> VersionNuspecTask: Change to find nuspec files in the root - Fixes #143

- Tests/Extensions/Versioning/VersionDacpacTask/Get-Toolpath.tests.ps1
Moved the VersionDacpacTask tests into a general Versioning folder. Also added a bit more mocking to tidy up the output from those tests.
> Move versioning tests into central location

- Extensions/Pester/PesterTask/Pester.ps1
The method of building the arguments for the x86 process appeared to be populating the $ModuleFolder variable when it shouldn't have. This modifies it to build it like a normal parameter string.
> Run32Bit not finding correct module path - Fixes #150

- Extensions/StyleCop/StyleCopTask/StyleCop.ps1
- Extensions/StyleCop/StyleCopTask/task.json
As we all know the first step in managing technical debt is stopping the rot. With that in mind, I've had a stab at adding an 'Allowable Violation Count' to the Task for StyleCop. The idea is that you can set a threshold which if you have fewer violations than the task doesn't error.
I'm afraid this is a new foray into PS and these tasks for me, so the change might be off but hopefully, it's helpful.
> StyleCopTask: Adding allowable violations count

- Extensions/StyleCop/StyleCopTask/StyleCop.ps1
Sorry, my previous PR broke this and just I noticed it on one of my builds. While I was using OverallSuccess to control the content of the message I wasn't evaluating it to decide if the task should error or not. This resulted in the build erroring if the flag was set and the there were violations.
> Fix "Test Errors as Warnings" flag being ignored

- Extensions/BuildUpdating/BuildVariableTask/BuildVariableTask.ps1
- Extensions/BuildUpdating/readme.md
As raised in #168 there is a problem with updating build variables using the old api versions as it removes the variable groups and other features that have been added. 
Changes appear to be more than actually needed as vscode decided to tidy up the style a little with trailing spaces etc being removed.
> Update to use api version 4 when updating build variables -Fixes #168

- Extensions/Versioning/VersionDotNetCoreAssembliesTask.src/ApplyVersionToAssemblies.ts
- Extensions/Versioning/readme.md
Added some extra regex to check if the `</TargetFramework>` or `</TargetFrameworks>` is present use whichever is there (see #166).
Also added a fix for #167 by changing the default field used to Version rather than AssemblyVersion as Version also effects Product Version field in the final output.
> Fix .Net Core versioning with targeting multiple frameworks. -Fixes #166 #167

- Extensions/Versioning/VersionDotNetCoreAssembliesTask.src/ApplyVersionToAssemblies.ts
- Extensions/Versioning/readme.md
Following the fixes in #182 it appears the regex broke the versioning so it always replaces all instances of the build number regex with the build number. This impacted nuget packages when using x.x.x version numbers.
> Fix .Net Core versioning of all uses of version numbers - Fixes #183

- Extensions/Versioning/VersionDotNetCoreAssembliesTask.src/ApplyVersionToAssemblies.ts
- Extensions/Versioning/readme.md
Building on @esbenbach's changes to also cover the cases where a user could specify the name of a field to use but it was in a different format to the provided version number and regex.
Updated the readme for both changes as well.
> Replicate esbenbach changes to catch if field was specified but version format differs - fixes #185

- Extensions/Versioning/VersionAssembliesTask/ApplyVersionToAssemblies.ps1
- Extensions/Versioning/readme.md
Previously the file searching was looking in Properties and similar folders but didn't account for specifying a location which had the assembly version file in the root of that path.
> Update filter to just look for specified file in any location under path - fixes #177

- Extensions/Versioning/VersionDacpacTask/Update-DacPacVersionNumber.ps1
- Extensions/Versioning/readme.md
Adds the SQL Server locations under `C:\Program Files (x86)` as it is the new install location of the DacFx files.
> Add new locations for DacPac dlls to versioning tasks - Fixes #197

- Extensions/Pester/task/Pester.ps1
- Extensions/Pester/test/PesterTask/Pester.Tests.ps1
- Extensions/Versioning/VersionDacpacTask/test/Get-Toolpath.tests.ps1
See #202 for details but short version is that some tests weren't loading the version of pester that shipped with the task and therefore the later tests were running using whichever version of Pester was available on the machine. This was causing some issues with mocking and more due to usually loading an older version.
> Update pester tests to use version with task.

- Extensions/Versioning/VersionJSONFileTask/src/ApplyVersionToJSONFile.ts
- Extensions/Versioning/VersionJSONFileTask/task/task.json
- Extensions/Versioning/readme.md
Add option to to apply a build number directly for a JSON file without any version number extraction processing
> Add option to to use a build number directly

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
As per issue #315, the override should be working properly if linked to the proper input name
difference between input name in task.json and input used in task code
#315 
- Added a new release line entry in to the extensions readme.md file (the list is usually found at the end of the file) that 
- increments the minor version number e.g. 1.2 to 1.3
- lists the Issue/PR number related to the change
- provides a brief single line comment as to the change made
- if the change adds new parameters update the appropriate documentation
> Fix parameter name

- Extensions/Pester/readme.md
- Extensions/Pester/task/HelperModule.psm1
- Extensions/Pester/test/PesterTask/Helper.Tests.ps1
Language.Parser can safely parse strings into their hashtable version and handles a few more use cases, like missing } and odd strings with ; and such in them. 
Added support for arrays of hashtables as well since you provide 1 per file you want to pass parameters to.
> Swap to using Language.Parser to parse the input string -fixes #321

- Extensions/Pester/readme.md
- Extensions/Pester/task/Pester.ps1
- Extensions/Pester/test/PesterTask/Parameters.Tests.ps1
- Extensions/Pester/test/PesterTask/Pester.Tests.ps1
Logging was using Write-Verbose but that doesn't output correctly in a build without System.Debug = True, which also forces all the other stuff to be verbose and can pollute the logs with tons of stuff you don't care about.
Using Write-Host ensures it#'s actually logging things out properly without System.Debug
> Pester parameter logging swapped to Write-Host - fixes #320

- Extensions/Pester/readme.md
- Extensions/Pester/task/Pester.ps1
- Extensions/Pester/test/PesterTask/Pester.Tests.ps1
Fixes #330 as the if check was using the wrong key name to check for, resulting in the code coverage always being based on the ScriptFolder which might be different to the test folder.
> Update to correctly generate code cov from specified folder - fixes #330

- Extensions/Pester/readme.md
- Extensions/Pester/task/Pester.ps1
- Extensions/Pester/task/task.json
- Extensions/Pester/test/PesterTask/Pester.Tests.ps1
The complex version loading logic was more convoluted than it needed
to be. Simplify it down to just always installing the latest version
if PSv5+ or PowerShellGet is available. If not then import the module
shipped with the task.
#312
- Added a new release line entry in to the extensions readme.md file (the list is usually found at the end of the file) that 
- increments the minor version number e.g. 1.2 to 1.3
- lists the Issue/PR number related to the change
- provides a brief single line comment as to the change made
- if the change adds new parameters update the appropriate documentation
- If you are willing, please enable me, as the Repo owner, to [edit your fork that contains your PR](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) …
> Remove extra functionality for handling module versions -fixes #312

- Extensions/Pester/task/Pester.ps1
If there are multiple repos available to a build agent then the returned object from Find-Module will be an array which won't correctly compare against a normal version number. As we're assuming we'll install from the PSGallery then the task should use that as it's latest version too.
> Fix to always check PSgallery for latest version in case of multiple repos

- Extensions/Versioning/VersionPowerShellModule/src/Update-PowerShellModuleVersion.ps1
- Extensions/Versioning/readme.md
Configuration module is not correctly loading when using Import-Module so use Get-Command to enumerate the available commands.
Fix a typo as well.
> Fix powershell versioning task

- Extensions/Versioning/VersionDotNetCoreAssembliesTask/src/AppyVersionToAssembliesFunctions.ts
Some tabs were left over in the dotnetcore versioning task and tslint prefers spaces.
> Change tabs to spaces as tslint doenst like them

- Extensions/Versioning/VersionPowerShellModule/src/Update-PowerShellModuleVersion.ps1
Logic wasn't catching if the module wasn't installed already, now it should check that the module is there before checking it's version number.
> fix logic to test for module first and then check for version installed

- Extensions/Pester/readme.md
- Extensions/Pester/task/Pester.ps1
- Extensions/Pester/task/task.json
Default path variable Build.SourceDirectory is only a valid variable in build. This updates the path to use System.DefaultWorkingDirectory which is available in both.
Also tidied up the error message produced by the ValidateScript on ResultsFile to make it more obvious why it failed.
> update default path variable to work in build and release - Fixes #350

- Extensions/Pester/readme.md
- Extensions/Pester/task/Pester.ps1
- Extensions/Pester/test/PesterTask/Pester.Tests.ps1
Version checking was looking at strings and sometimes having issues when the version was higher but the string didn't correctly compare as being higher.
> Fix version check in Pester task.

- Extensions/Pester/task/HelperModule.psm1
SafeGetValue doesn't exist in lower versions of PowerShell which is
causing exceptions when trying to run the HelperModule.
> Add support for PowerShell v4 and lower in hashtable parsing

- Extensions/Pester/readme.md
- Extensions/Pester/task/Pester.ps1
- Extensions/Pester/test/PesterTask/Pester.Tests.ps1
PSGallery isn't always available so this will choose the first available repository and use that.
> Fix repository Pester is downloaded from

- Extensions/BuildUpdating/BuildRetensionTask/BuildRetensionTask.ps1
- Extensions/BuildUpdating/BuildVariableTask/BuildVariableTask.ps1
- Extensions/BuildUpdating/readme.md
FIxes the build tasks so they can use the new Azure DevOps URLs
> #380 fix for dev.azure.com URLs

- Extensions/Versioning/VersionAndroidManifest/src/ApplyVersionToManifest.ts
- Extensions/Versioning/readme.md
If the versionCode is 0 then it's not accepted, the build should fail if this is the case.
#387
> ensure versionCode is not set to 0 - Fixes #387

- Extensions/Versioning/VersionSharepointAppManifestTask/ApplyBuildVersionToSharepointAppManifest.ps1
- Extensions/Versioning/readme.md
A comma was missed out of the parameter block for the Sharepoint versioning task and this is causing the task to fail.
> Add missing comma to param block for SharePoint versioning -Fixes #406

- Extensions/Pester/readme.md
- Extensions/Pester/task/Pester.ps1
Find-Module was sometimes finding prerelease versions of Pester. This was causing it to fail as System.Version can't handle semantic versioning.
#412 
- Added a new release line entry in to the extensions readme.md file (the list is usually found at the end of the file) that 
- increments the minor version number e.g. 1.2 to 1.3
- lists the Issue/PR number related to the change
- provides a brief single line comment as to the change made
- if the change adds new parameters update the appropriate documentation
> Force -AllowPrerelease to be false when calling Find-Module

- Extensions/Pester/readme.md
- Extensions/Pester/task/Pester.ps1
Reverts rfennell/AzurePipelines#413
There are issues with this fix and we need to spend some more time on working on a better fix to this and testing it more thoroughly.
> Revert "Force -AllowPrerelease to be false when calling Find-Module"

- Extensions/Pester/readme.md
- Extensions/Pester/task/Pester.ps1
When no internet access was available to download nuget the task was failing. Now we fall back to the shipped version of pester.
> Add catch to fallback to shipped pester if can't download nuget -fixes #447

- Extensions/Versioning/VersionDotNetCoreAssembliesTask/task/task.json
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/tsconfig.json
The Version .NET Core Assemblies task fails when executed on a TFS 2015.4 build agent.
https://github.com/rfennell/AzurePipelines/issues/457
- Added a new release line entry in to the extensions readme.md file (the list is usually found at the end of the file) that 
- increments the minor version number e.g. 1.2 to 1.3
- lists the Issue/PR number related to the change
- provides a brief single line comment as to the change made
- if the change adds new parameters update the appropriate documentation
> NOTE: I did not modify readme.md as there was no existing release history in this one. Also, it seems that you have a separate versioning system so I wasn't sure if you needed any versions bumped in your PR.
- If you are willing, please enable me, as the Repo owner, to [edit your fork that …
> Fix Version .NET Core Assemblies fails with "Unexpected token ="

- Extensions/Versioning/VersionDotNetCoreAssembliesTask/src/AppyVersionToAssembliesFunctions.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/FileProcessingTest.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/FindFilesTests.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/testdata/core494.csproj.expected
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/testdata/core494.csproj.initial
Fix for the .NET Core versioner. The switch to regex for block matching causing a problem if there are duplicate blocks. Now assume that we use the first block found.
> #494 fixes to the regex matching for multiple matches

- Extensions/WikiUpdater/WikiUpdaterTask/package-lock.json
- Extensions/WikiUpdater/WikiUpdaterTask/package.json
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
Add a reference that has not been reported by Typescript, but seems to be a problem in production
> Add a reference to the process NPM package

- Extensions/Versioning/VersionDacpacTask/src/Update-DacPacVersionNumber.ps1
- Extensions/Versioning/readme.md
Add support for versioning SqlProj files to set the DacPac version pre-build
VersionDacPac would only run post build due to modifying the produced DacPac file. This was causing issues on large DacPacs as it has to validate the file. This PR adds a check to see if any DacPacs have been generated and if not it will modify the sqlproj file and add the DacVersion property to set the version as part of the build.
#486
> Add support for versioning SqlProj files to set the DacPac version - fixes #486

- Extensions/Versioning/VersionDacpacTask/src/Update-DacPacVersionNumber.ps1
RegexMatch doesn't convert to System.Version neatly, need to add a call to parse it.
> Ensure version number gets parsed from a regex match

- Extensions/BuildUpdating/BuildVariableTask/BuildVariableTask.ps1
- Extensions/BuildUpdating/readme.md
1.15.x introduced a regression so variable groups could not be updated
Logic has been added to pick the correct API version to support TFS 2017 (2.0 or 3.0) and variable groups in later versions of Azure DevOps (4.0)
> Fix regression in build variables for resource groups

- Extensions/Versioning/VersionPowerShellModule/src/Update-PowerShellModuleVersion.ps1
- Extensions/Versioning/VersionPowerShellModule/test/Update-PowerShellModuleVersion.Tests.ps1
Versioning PowerShell modules doesn't handle prerelease versioning, this will fix that by adding the prerelease flag to the PrivateData section of the manifest.
#547
> Add support for specifying prerelease flags in the versioning of PowerShell modules -Fixes #547

- Extensions/XplatGenerateReleaseNotes/V2/task.json
Generate Release Notes (Crossplatform)
This PR is a small one to make the display name of the extension and the task be consistent between the two .json files (task.json and vss-extension.json).  This avoids some minor confusion in the DevOps UI.
no
> Coordinate names

- Extensions/Versioning/VersionAngularFileTask/src/AppyVersionToAngularFileFunctions.ts
- Extensions/Versioning/VersionAngularFileTask/test/FileProcessingTest.ts
- Extensions/Versioning/VersionAngularFileTask/test/FindFilesTests.ts
- Extensions/Versioning/VersionAngularFileTask/test/testdata/issue615-environment.ts.expected
- Extensions/Versioning/VersionAngularFileTask/test/testdata/issue615-environment.ts.initial
Addresses issue #614
Allows the use of double quotes in the `environment.ts` file to be versioned.
> Angular Version: allow the use of double quotes for the version field

- Extensions/Versioning/VersionDacpacTask/test/File-Processing.tests.ps1
Fixes a problem that though all the DACPac test run locally they fail in a build agent
> Added $PSScriptRoot to the paths

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V2/package-lock.json
- Extensions/XplatGenerateReleaseNotes/V2/package.json
- Extensions/XplatGenerateReleaseNotes/package-lock.json
- Extensions/XplatGenerateReleaseNotes/package.json
- Extensions/XplatGenerateReleaseNotes/readme.md
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 2/release-handlebars-template.md
Existing template capabilities are limited.  Enabling use of a library such as Handlebars gives the user much more power and flexibility over the rendered markup.
N/A
Please take a look at my proposed change to allow Handlebars templates.  I think it's a pretty simple change that would greatly enhance the extension.   Please note that I do not have a way to test this, so while I tried to be as careful as possible with the code, it's ultimately more of a proposal for changes than a guarantee of the working change.
Because I tabbed everything over when wrapped the guts of the processTemplate in an IF statement, the diff looks pretty ugly - but in a nutshell, all I really did was the following:
1) added the npm handlebars package
2) modified the getTemplate function to detect a handlebar …
> Added support for Handlebars template library

- SampleTemplates/GenerateReleaseNotes (Original Powershell based)/build-git-with-azure-dev-ops-links.md
A build template that contains links for Azure DevOps commits and work items. Works great with the Wiki Updater extension.
Gives an example of how easy it is to add links to the generated release notes template
No
> Added build-git-with-azure-dev-ops-links.md

- Extensions/Pester/task/Pester.ps1
- Extensions/Pester/vss-extension.json
Pester. Handles failures downloading from the gallery (whichever gallery that might be).
#677 and #507 
> Handle gallery failure by falling back to shipped version of pester

- Extensions/XplatGenerateReleaseNotes/V3/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/task.json
- Extensions/XplatGenerateReleaseNotes/readme.md
#801 
Provides a means to inject a Personal Access Token to use in place of the Build Agent OAUTH token. This option will only be used in very rare situations usually after a support issue has been raised
> Exposed a way to inject a PAT

- Extensions/XplatGenerateReleaseNotes/V3/task.json
GenerateReleaseNotes Node based Cross Platform
- Avoid backslashes being interpreted as escape on non-Windows machines
Fixes #859
> Use forward slash as path separator

- Extensions/XplatGenerateReleaseNotes/readme.md
> Update the documentation over agent scope

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Split the error handling so release note generation always attempted even with API errors

- Extensions/XplatGenerateReleaseNotes/V3/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Swapped the return codes to highlight partial success

- Extensions/WikiPDFExport/WikiPDFExportTask/src/ExportFunctions.ts
- Extensions/WikiPDFExport/WikiPDFExportTask/src/WikiPDFExportTask.ts
- Extensions/WikiPDFExport/WikiPDFExportTask/task/task.json
- Extensions/WikiPDFExport/WikiPDFExportTask/test/testrunnerForSingleFile.ts
- Extensions/WikiPDFExport/WikiPDFExportTask/test/testrunnerForWikiWithNoClone.ts
- Extensions/WikiPDFExport/WikiPDFExportTask/test/testrunnerToCloneFromAzureDevOps.ts
- Extensions/WikiPDFExport/WikiPDFExportTask/test/testrunnerToCloneFromGitHub.ts
- Extensions/WikiPDFExport/azure-pipelines-build.yml
- Extensions/WikiPDFExport/readme.md
> Add support for partial export

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
We're trying to migrate our things to store from `Build Artifacts` to `Pipeline Artifacts` (`Universal packages` actually) for better permission control, see [Overview of Artifacts in Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/artifacts-overview?view=azure-devops).
However, as of XplatGenerateReleaseNotes@3.42.2, the [`artifactInThisRelease.artifactType === "Build"`](https://github.com/rfennell/AzurePipelines/blob/XplatGenerateReleaseNotes_3.42.2/Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts#L1069-L1169) is checked before getting build info from CI pipeline, which make the Pipeline Artifacts be bypassed with **no commit and work item info**.
I'm not trying to change those logic, but instead, to "hack" and restore the original …
> Support build info restoring when using Pipeline Artifacts

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
After merging #pr937 it was found that the process of getting WI/CS details could fail due to a missing project ID.
Code has been added to try two locations for the projects ID
- The originally used property
- If this is null then it falls back to the extracting the value from the JSON  
Also in the process of debuging this add a bit more logging
> Added a fail through check for the project ID

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
The PR history this new feature has been confused to the way I had to test the feature. Due to a limitation of my test I needed to merge to `main`, and then used a poor language construct
#937 #938
> Added a fail through check for the project ID (#938)

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
Azure DevOps Extensions - Generate Release Notes (Node Cross Platform)
Adding a null check for record.result
#1176: TypeError: Cannot read properties of null (reading 'toString')
> #1176: gaurding against null record.result

- Extensions/Versioning/VersionAndroidManifest/src/ApplyVersionToManifest.ts
- Extensions/Versioning/VersionAndroidManifest/src/ApplyVersionToManifestFunctions.ts
- Extensions/Versioning/VersionAndroidManifest/test/android.tests.ts
- Extensions/Versioning/VersionAngularFileTask/src/ApplyVersionToAngularFile.ts
- Extensions/Versioning/VersionAngularFileTask/src/AppyVersionToAngularFileFunctions.ts
- Extensions/Versioning/VersionAngularFileTask/test/FileProcessingTest.ts
Fixes #1180
Removes the edge case where invalid output formats are passed and a version is directly injected
> Revise handling of injectversion for Android and Angular versioner tasks

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
> Fix for WIKIUpdater if prepending a non-existent .order file

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
GeneratereleaseNotes (XPlat version)
Added relatedWorkItems to pipeline artifacts if getAllParents is enabled. This is similar to the data available for the primary artifact.
#1334 
> Added relatedWorkItems as additional parent data for pipeline artifacts

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
The WIQL flow was not handling the alternate return object for when the wiqlFromTarget was set to WorkItemLinks resulting in no errors but no results ever processed even when the query had results. Since various linkage types are returned I decided to just pull all and dedupe them.
Not positive if target?.id is the correct source for all flows though.
--[XplatGenerateReleaseNotes](https://github.com/rfennell/AzurePipelines/tree/main/Extensions/XplatGenerateReleaseNotes)--
--WIQL pull from workItemRelations for WorkItemLinks--
-- Fixes #1346 --
- If you are willing, please enable me, as the Repo owner, to [edit your fork that contains your PR](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) so I can add any missing items such as the …
> WIQL pull from workItemRelations for WorkItemLinks

- Extensions/ArtifactDescription/azure-pipelines.yml
- Extensions/BuildUpdating/azure-pipelines.yml
- Extensions/DevTestLab/azure-pipelines-build.yml
- Extensions/FileUtilities/azure-pipelines-build.yml
- Extensions/Versioning/azure-pipelines-build.yml
- Extensions/WikiPDFExport/azure-pipelines-build.yml
- Extensions/WikiUpdater/azure-pipelines-build.yml
- Extensions/XplatGenerateReleaseNotes/azure-pipelines-build.yml
- Extensions/YamlGenerator/azure-pipelines-build.yml
- YAMLTemplates/post-publish-tester.yml
- YAMLTemplates/post-publish.yml
In the past I used various tasks to do social media pushes when I released a new extension. I recently moved the twitter post (due to Twitter API changes) to a Logic App. After a bit more thought it seemed a good idea to move all social posts to this platform, so it matches the way I do post for blog post entries
> Update social media push

- Extensions/XplatGenerateReleaseNotes/azure-pipelines-build.yml
This is required to make sure the YAML based documentation is correctly created. This occurred because of the refactoring of the folder structure
> Fix the filter to find the task manifest

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts
Task: **XPlatGenerateReleaseNotesTask**
The current log message pretends to log the **Release Id & Status** but its actually logging the **Deployment's Id & Status** which is different, It causes confusion when debugging the logs,  In this PR I've fixed the message
> XPlatGenerateReleaseNotesTask: Fix log message about deployments found

- .vscode/launch.json
- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/testconsole/readme.md
- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/tsconfig.json
XplatGenerateReleaseNotes/testconsole
The files are moved as part of `npm run build` so
the sources in the .js.maps needs to be set accordingly, which
is what the sourceRoot property does here.
N/A
> fix: reenable vscode debug stepping

- .devcontainer/devcontainer.json
- Extensions/DevTestLab/privacy.md
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Adds more logging and null check to WIKI Updater #1569 
- Adds a Codespace definition so we now using a basic default
> Adds more logging and null check to WIKI Updater

- .vscode/launch.json
This env var is set for the Task in Azure and
affects the data retrieved so it should also
be set when using the test console
XplatGenerateReleaseNotes test console
--add Issue number--
#1563 
Does not fully resolve the issue (running the test console without debugging does not get the env var set) but is a step in that direction
> fix: replicate important env var for debugging

- Extensions/WikiPDFExport/WikiPDFExportTask/package-lock.json
- Extensions/WikiPDFExport/WikiPDFExportTask/package.json
- Extensions/WikiPDFExport/WikiPDFExportTask/src/GitWikiFunctions.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/package-lock.json
- Extensions/WikiUpdater/WikiFolderUpdaterTask/package.json
- Extensions/WikiUpdater/WikiFolderUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/package-lock.json
- Extensions/WikiUpdater/WikiUpdaterTask/package.json
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
> Revert to rimraf 3.0.2 to restore support for V2 Agents using Node10 support

- Extensions/WikiPDFExport/WikiPDFExportTask/task/task.json
- Extensions/WikiPDFExport/test-stage.yml
- Extensions/WikiUpdater/WikiFolderUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/multi-file-test-steps.yml
- Extensions/WikiUpdater/single-file-test-steps.yml
- YAMLTemplates/generate-wiki-docs.yml
Remove V2 Agent (Node10 execution engine) support for the WIKI related tasks WIKIPDFExporter and the two WIKIUploader tasks.
This is to allow the update of the rimraf library to a later version than 3.0.2 (V4 and later need Node14 and later)
> Remove V2 Agent (Node10 execution engine) support for the WIKI related tasks

- Extensions/WikiPDFExport/readme.md
Updated sample to use `WikiPdfExportTask@4` instead of `@2`
> Update readme.md (to use `@4` instead of `@2`

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts
Azure DevOps Extensions - Generate Release Notes (Node Cross Platform)
Adding guard clause to solve issue with manually uploaded artifacts which don't have build id associated
#1966 
> add guard clause to skip artifact with missing build associated

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts
**GenerateReleaseNotes (XPlat version)**
Resolves #2021 by html encoding the `teamProject` variable before it is used to create the request url for getting consumed artifacts.
It also adds some debugging messages and additional warning information in case the request or the subsequent processing of the request result fails.
#2021
> add html encoding for project when getting consumed artifacts

- Extensions/Versioning/VersionPowerShellModule/src/Update-PowerShellModuleVersion.ps1
- Extensions/Versioning/VersionPowerShellModule/src/task.json
- Extensions/Versioning/VersionPowerShellModule/test/Update-PowerShellModuleVersion.Tests.ps1
- Extensions/Versioning/azure-pipelines-build.yml
> Adds option to not recurse when searching for files

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/task/task.json
Added the runner execution block for Node20, but leaving all the existing execution blocks for Node16 and Node 10.  They all use JS scripts file.
fixes #2106
> Added Node 20 Support

- Extensions/WikiUpdater/WikiFolderUpdaterTask/WikiFolderUpdaterTaskV3/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV3/task/task.json
Added the runner execution block for the V3 tasks to  Node20, but leaving  the existing execution blocks for Node16. They  use JS scripts file.
fixes #2106
> Add Node20 support
