rfennell/AzurePipelines

- Tasks/VersionDacpac/Update-DacPacVersionNumber.ps1
- Tasks/VersionDacpac/task.json
updated script to accept string instead for use with $(build.buildnumber) environment variables in TFS.
> updated script 

- Extensions/Pester/PesterTask/Pester.ps1
- Extensions/Pester/PesterTask/task.json
- Extensions/Pester/readme.md
- Tests/Extensions/Pester/PesterTask/Pester.Tests.ps1
> Pester: Adding Tag and ExcludeTag parameter support

- Extensions/Versioning/VersionDacpacTask/Update-DacPacVersionNumber.ps1
- Tests/Extensions/VersionDacpacTask/Get-Toolpath.tests.ps1
Added support fro VS2017 and SQL2016
> Added support for new version #86

- Extensions/XplatGenerateReleaseNotes/XPlatGenerateReleaseNotesTask.src/ReleaseNotesFunctions.ts
Added support for redeploys
Fixed an issue with deploying older releases than current
Fixed an issue where changesets where included when they shouldn't be
> Various Fixes

- Extensions/FileUtilities/readme.md
- Extensions/Versioning/readme.md
- Extensions/XplatGenerateReleaseNotes/readme.md
The markdown for a few extensions needs updating as raised in #170 for the new parser being used in the marketplace.
> Fix markdown for various extensions -fixes #170

- .vscode/launch.json
- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.ps1
- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.psm1
- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/task.json
- Extensions/GenerateReleaseNotes/readme.md
- Extensions/GenerateReleaseNotes/test/localrun.tests.ps1
- Extensions/GenerateReleaseNotes/test/runtests.ps1
- Extensions/GenerateReleaseNotes/vss-extension.json
Merge Swarnberg PR Includes parent Work Items #221 plus other enhancements
- Includes parent Work Items #221
- Added option flag to enable parent wi handling
- Added ability to append resultant release notes file as discussed in Issue #224
> Merge Swarnberg PR Includes parent Work Items #221

- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.ps1
- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.psm1
- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/task.json
- Extensions/GenerateReleaseNotes/readme.md
- Extensions/GenerateReleaseNotes/test/localrun.tests.ps1
- Extensions/GenerateReleaseNotes/test/runtests.ps1
- SampleTemplates/GenerateReleaseNotes (Original Powershell based)/release-basic-unfied-template.md
Provides a means to roll up the work items and changsets/commits in all the builds as a single list
> Issue257 - Provide a means to roll up wi/cs

- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.ps1
- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.psm1
With this update this Task will be able to make http call to internet when running in Private Agent with a Proxy.
> Transparent proxy usage

- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.ps1
- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.psm1
- Extensions/GenerateReleaseNotes/readme.md
@Aldodfm PR #267 with an update to the readme file
> Aldodfm behind proxy

- Extensions/Pester/readme.md
- Extensions/Pester/task/HelperModule.psm1
- Extensions/Pester/task/Pester.ps1
- Extensions/Pester/task/task.json
- Extensions/Pester/test/PesterTask/Helper.Tests.ps1
- Extensions/Pester/test/PesterTask/Pester.Tests.ps1
> Issue265 Allow -script @{} format parameters to be used

- Extensions/Pester/test/PesterTask/Pester.Tests.ps1
Adds some new tests for the additional module path functionality and the new parameters.
> Add extra tests for addtional module path

- Extensions/Versioning/VersionDotNetCoreAssembliesTask/src/ApplyVersionToAssemblies.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/src/AppyVersionToAssembliesFunctions.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/task/task.json
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/FileProcessingTest.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/testdata/coremissingaddversion.csproj.expected
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/testdata/coremultiple.csproj.expected
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/testdata/coremultiple.csproj.initial
- Extensions/Versioning/readme.md
#302  Adds a default version field if missing (optional)
> Issue302 Adds a default version field

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
Fixes a minor issue with the log output.
> Fixes logging issue

- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.psm1
- Extensions/GenerateReleaseNotes/readme.md
- Extensions/Versioning/readme.md
- Extensions/XplatGenerateReleaseNotes/V1/package-lock.json
- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V2/Issue349Workaround.ts
- Extensions/XplatGenerateReleaseNotes/V2/package-lock.json
- Extensions/XplatGenerateReleaseNotes/package-lock.json
- Extensions/XplatGenerateReleaseNotes/readme.md
There is a limitation in the TFS/VSTS build APIs that can lead to incomplete list of work items associated to a build.
Yes, see issue #349 
The PR has not been thoroughly tested yet as I am just building a sample project that exhibits the problem and allows testing. I will update the PR with a comment once that is done. Any additional testing with existing standard builds/releases is highly appreciated ;-)
> Workaround for TFS/VSTS API limitation (issue #349)

- scripts/Generate-YAMLDocumation.ps1
Added a tool that allows generation of markdown from the task.json
> Documentation

- Extensions/BuildUpdating/BuildVariableTask/BuildVariableTask.ps1
Fixed a typo just noticed on code push to master
> #374 Fixed a typo

- Extensions/Versioning/VersionNuspecTask/task.json
Fixes the typo in the help text
> #427 fixed typo

- Extensions/Versioning/VersionAndroidManifest/src/ApplyVersionToManifestFunctions.ts
- Extensions/Versioning/VersionAndroidManifest/test/android.tests.ts
- Extensions/Versioning/VersionAndroidManifest/test/testdata/435.xml.expected
- Extensions/Versioning/VersionAndroidManifest/test/testdata/435.xml.initial
#435 Added extra code to filter so no extra version code fields are updated
> Added extra code to filter so no extra version code fields are updated

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
#327 added logic to get the work items for the first release of a new pipeline
> #327 added logic to get the work items for the first release

- Extensions/WikiUpdater/WikiUpdaterTask/package-lock.json
- Extensions/WikiUpdater/WikiUpdaterTask/package.json
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/dummy.test.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/foldercreation.test.ts
- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
Adds the ability to place wiki pages in folders
> Issue442 wiki paths

- Extensions/Versioning/VersionPowerShellModule/src/Update-PowerShellModuleVersion.ps1
- Extensions/Versioning/VersionPowerShellModule/test/Update-PowerShellModuleVersion.Tests.ps1
Add extra checks to ensure Configuration is downloaded from available gallery 
Also checks to ensure nuget is available and can be downloaded. If not fallback to shipped version of module.
> Add extra checks to ensure Configuration is downloaded from available gallery - fixes #434

- Extensions/DevTestLab/StartVM/task.json
- Extensions/DevTestLab/StopVM/task.json
- Extensions/DevTestLab/readme.md
DevTest Lab Tools documentation update
> #466 updated the documentation

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V2/agentSpecific.ts
- Extensions/XplatGenerateReleaseNotes/V2/task.json
- Extensions/XplatGenerateReleaseNotes/readme.md
Puts a stop of task if a deploy
> #440 stops generation if a redeploy

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/azure-pipelines-build.yml
- Extensions/WikiUpdater/readme.md
- Swapped to YAML build
- Added extra pull check
- Add doc stage to deployment
> Issue478 wiki concurrency

- Extensions/Versioning/VersionAssembliesTask/task.json
Removes the required flag and visibility rules for the regex express
> Changes for #473 - change visibily rules

- .vscode/launch.json
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/package-lock.json
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/package.json
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/src/AppyVersionToAssembliesFunctions.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/FileProcessingTest.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/FindFilesTests.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/testdata/core483.csproj.expected
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/testdata/core483.csproj.initial
Updates the processing to only look at the primary <PropertyGroup>
> Issue483 Version dotnetcore

- Extensions/Versioning/VersionAngularFileTask/src/AppyVersionToAngularFileFunctions.ts
- Extensions/Versioning/VersionAngularFileTask/task/task.json
- Extensions/Versioning/VersionAngularFileTask/test/FileProcessingTest.ts
- Extensions/Versioning/VersionAngularFileTask/test/FindFilesTests.ts
- Extensions/Versioning/VersionAngularFileTask/test/testdata/environment.dev.ts
- Extensions/Versioning/VersionAngularFileTask/test/testdata/environment.prod.ts
- Extensions/Versioning/VersionAngularFileTask/test/testdata/environment.prod.ts1
> Add the option to used regex for the file name match in Angular

- Extensions/Versioning/VersionAngularFileTask/package.json
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/package.json
- Extensions/Versioning/VersionJSONFileTask/package-lock.json
- Extensions/Versioning/VersionJSONFileTask/package.json
- Extensions/Versioning/azure-pipelines-build.yml
> Added synk support to node based version tasks

- Extensions/BuildUpdating/vss-extension.json
- Extensions/DevTestLab/vss-extension.json
- Extensions/Pester/vss-extension.json
- Build Utils
- DevTest Labs
- Generate Release Notes
> Move the Marketplace Q&A to Github Issues

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/vss-extension.json
#515 add a message in log to make this clear
> Moved QA to Gthub and added run in build check

- Extensions/BuildUpdating/BuildVariableTask/BuildVariableTask.ps1
> Reverted the API calls for variable Update to 2.0 from 4.0 for backwards compatibility

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V2/test/test-misc.ts
Fixes the compare
Fixes a stray test that had not been committed correctly on past work
> #565 a fix to that the compare is not done on build name but the id

- Extensions/Versioning/VersionJSONFileTask/src/AppyVersionToJSONFileFunctions.ts
- Extensions/Versioning/VersionJSONFileTask/task/task.json
- Extensions/Versioning/VersionJSONFileTask/test/FileDiscoveryTest.ts
- Extensions/Versioning/VersionJSONFileTask/test/testdata/folder1/not-package.json.initial
- Extensions/Versioning/VersionJSONFileTask/test/testdata/not-package.json.initial
I've implemented the same pattern as #490 and added some tests
See #569 
Thanks!
> Use wildcard regex as fall back when finding Json files

- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V2/test/testmodes.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 2/release-with-WI-filter.md
> Allow ALL or ANY matching of tags for WI filtering

- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/task.json
- Extensions/GenerateReleaseNotes/readme.md
- Extensions/GenerateReleaseNotes/vss-extension.json
Updated the documentation to let people know that the Cross platform release note are better
> Updated the documentation

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V2/task.json
- Extensions/XplatGenerateReleaseNotes/V2/test/test-misc.ts
- Extensions/XplatGenerateReleaseNotes/V2/test/testmodes.ts
- Extensions/XplatGenerateReleaseNotes/V2/test/testsuite.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 2/release-with-WI-filter.md
> Add support to filter work item list on field contents as well as tags

- Extensions/Versioning/VersionDotNetCoreAssembliesTask/src/AppyVersionToAssembliesFunctions.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/task/task.json
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/FileProcessingTest.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/FindFilesTests.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/testdata/directory.build.props.expected
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/testdata/directory.build.props.initial
- Extensions/Versioning/readme.md
#346
It looks as if this has been present for a while due to changes in the way file checks are made.
Added tests and documentation
> Add support for directory.build.props files

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/readme.md
> Added a pre-pend option when writing to wiki

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/readme.md
> Add a tag feature to wiki updater 

- Extensions/Versioning/VersionDotNetCoreAssembliesTask/src/AppyVersionToAssembliesFunctions.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/FileProcessingTest.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/FindFilesTests.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/testdata/core589.csproj.expected
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/testdata/core589.csproj.initial
- Extensions/Versioning/azure-pipelines-build.yml
> Improve code to find any exiting version fields for.NETCore Versioner

- Extensions/DevTestLab/StopVM/task.json
- Extensions/DevTestLab/azure-pipelines-build.yml
> fixed bug so start and stop tasks don't have same name, making task usable in YAML 

- Extensions/Versioning/VersionDacpacTask/src/Update-DacPacVersionNumber.ps1
- Extensions/Versioning/VersionDacpacTask/test/File-Processing.tests.ps1
- Extensions/Versioning/VersionDacpacTask/test/testdata/Issue603.sqlproj.expected
- Extensions/Versioning/VersionDacpacTask/test/testdata/Issue603.sqlproj.initial
> fix file UTF8 encoding for .sqlproj file

- Extensions/YamlGenerator/YamlGeneratorTask/package-lock.json
- Extensions/YamlGenerator/YamlGeneratorTask/package.json
- Extensions/YamlGenerator/YamlGeneratorTask/src/Generate-YAMLDocumentation.ts
> Correct bug so can check for all input groups

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V2/task.json
- Extensions/XplatGenerateReleaseNotes/readme.md
> Added a primary artifact only filter

- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
> Added a handler for expanding commit messages on GitHub repos

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/readme.md
> Provide optional injection of extra authentication header on the clone

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
> Added logic to iterate across all prior builds not just the last

- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
> Add code to skip the line expand if not required to allow HTML formatting

- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V2/test/testmodes.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Added an optional regex filter on commits/changeset message

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V2/task.json
- Extensions/XplatGenerateReleaseNotes/readme.md
> Added a wild card option when matching field content

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Exposes the triggering build so it can be used in a template

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V2/package-lock.json
- Extensions/XplatGenerateReleaseNotes/V2/package.json
- Extensions/XplatGenerateReleaseNotes/V2/task.json
- Extensions/XplatGenerateReleaseNotes/readme.md
> Add support for handlebar helpers

- Extensions/XplatGenerateReleaseNotes/V2/Issue349Workaround.ts
> Added missing commentTruncated property to commit object

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
Also fixes a typo in a log message
#654
> Builds the temp folder to store the handles custom code in differently

- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V2/package-lock.json
- Extensions/XplatGenerateReleaseNotes/V2/package.json
- Extensions/XplatGenerateReleaseNotes/V2/test/test-misc.ts
> Set the file encoding to UTF8 when reading and writing files

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Added means to make PR details available in template

- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.ps1
- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/task.json
- Extensions/GenerateReleaseNotes/readme.md
> Add a flag for generating release notes on trigger artifact

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
> Added logic to avoid trying to match null object when searching for PRs

- Extensions/Versioning/VersionWixTask/ApplyBuildVersionToWix.ps1
- Extensions/Versioning/VersionWixTask/task.json
- Extensions/Versioning/readme.md
> Made the list of fields to update configurable for WIX files

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
> Changed logic on the way PRs are matched

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V2/task.json
- Extensions/XplatGenerateReleaseNotes/readme.md
> Add option to search for PRs cross team project 

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/azure-pipelines-build.yml
- Extensions/WikiUpdater/readme.md
> Added ability to checkout a pre-existing branch and commit to it as opposed to master

- Extensions/Pester/task/Pester.ps1
- Extensions/Pester/task/task.json
- Extensions/Pester/vss-extension.json
Deprecate Pester extension to move it to a new repo and publisher.
> deprecate the pester extension

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 2/Handlebars/release-handlebars-dump-template.md
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 2/Handlebars/release-handlebars-template.md
Adds tests as objects that can be referenced in Handlebars based templates
#716
> Add support for accessing test results in handlebars based templates

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/azure-pipelines-build.yml
- Extensions/XplatGenerateReleaseNotes/readme.md
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 2/Handlebars/release-handlebars-template.md
> Add list of files changed in Commit or Changeset

- Extensions/XplatGenerateReleaseNotes/V2/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V2/task.json
- Extensions/XplatGenerateReleaseNotes/readme.md
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 2/Handlebars/release-handlebars-template.md
> Added in code to build the parent and child relationship

- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
> Improve error handling when template is missing or contain errors

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/azure-pipelines-build.yml
- Extensions/WikiUpdater/readme.md
> Improve docs and various fixes

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
> Wrong file name listed in error log message

- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
> Added a try catch on initial run to improve error logging

- Extensions/WikiUpdater/WikiFolderUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/azure-pipelines-build.yml
- Extensions/WikiUpdater/readme.md
> Added logic to allow a repo URL to pasted in from the source without manual editing to trim it 

- Extensions/XplatGenerateReleaseNotes/V2/ReleaseNotesFunctions.ts
> Added extra trap to continue on error

- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 3/gitflow-extension.js
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 3/gitflow-readme.md
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 3/gitflow-template.hbs
Adds a custom template
Fixes #760
> Adds sample template for GitFlow support (#760)

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Fix bug that file name enrichment not done on all paths

- Extensions/XplatGenerateReleaseNotes/V3/testconsole/GenerateReleaseNotesConsoleTester.ts
> Made sure the checkStage variable is read as a boolean

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/task.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/build-settings.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/release-settings.json
> Make sure the parameters passed in by tester are used

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/task.json
> Add check that there is timeline data for a build to avoid null error

- .vscode/launch.json
- Extensions/XplatGenerateReleaseNotes/V3/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/package-lock.json
- Extensions/XplatGenerateReleaseNotes/V3/package.json
- Extensions/XplatGenerateReleaseNotes/V3/task.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/GenerateReleaseNotesConsoleTester.ts
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/readme.md
- Extensions/XplatGenerateReleaseNotes/readme.md
> Add support for getting full commit message details from Bitbucket

- Extensions/XplatGenerateReleaseNotes/V3/testconsole/GenerateReleaseNotesConsoleTester.ts
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 3/return_parents_only.js
> Added a template to list just parent WI

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/agentSpecific.ts
- Extensions/XplatGenerateReleaseNotes/V3/test/fileEncoding.test.ts
- Extensions/XplatGenerateReleaseNotes/V3/test/sort.test.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Attempt to use a different method to get the access token

- Extensions/WikiUpdater/WikiFolderUpdaterTask/test/geturl.test.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/geturl.test.ts
When tiding the .gitignore found these tests that were present on my development PC but excluded from source control
> Add a pair of test that had been incorrectly excluded

- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 3/build-handlebars-template.md
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 3/get_only_message_firstline.js
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 3/release-handlebars-template.md
- Correct sample with correct way to get Pull Request ID
- Added handlebars sample to get just the first line of a multi-line string
> Template and sample fixes

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Add the compareBuildDetails object for use in multi-stage YAML pipelines

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Fixes a incorrect match due to inferred types

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Added details of the timeline for multistage YAML if checkstage is enabled

- Extensions/XplatGenerateReleaseNotes/V3/Issue349Workaround.ts
> Add a null check to the gitClient.getCommitsBatch() result processor

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Add a larger default for the code paths that don't used #349 fix

- Extensions/WikiUpdater/WikiFolderUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiFolderUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/readme.md
> Issue808 wiki retry

- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.ps1
- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/GenerateReleaseNotes.psm1
- Extensions/GenerateReleaseNotes/GenerateReleaseNotesTask/task.json
- Extensions/GenerateReleaseNotes/readme.md
--added option to include only builds with specific tag/tags
> added option to include only builds with specific tag/tags

- Extensions/XplatGenerateReleaseNotes/V3/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/task.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/GenerateReleaseNotesConsoleTester.ts
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/build-settings.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/release-settings.json
- Extensions/XplatGenerateReleaseNotes/readme.md
> Add full recursion for parents

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Add an extra try catch for unhandle exceptions

- Extensions/XplatGenerateReleaseNotes/V3/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/task.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/GenerateReleaseNotesConsoleTester.ts
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/build-settings.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/release-settings.json
- Extensions/XplatGenerateReleaseNotes/readme.md
> Added support for pipeline tag filtering in YAML builds

- Extensions/WikiPDFExport/readme.md
- Extensions/WikiUpdater/readme.md
Adds more troubleshooting details for OAUTH
> Documentation update for WIKI tools

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Added an extra null check when no WI returned

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Added null check for pre-approval-deployment

- Extensions/WikiPDFExport/WikiPDFExportTask/task/task.json
> Remove the settings that will not validate for Server 2019

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Moves the default location for loading custom modules

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/readme.md
fixes #826 but you do have to set an extra parameter ` trimLeadingSpecialChar=true` as I don't want to introduce a breaking change
> Add the option to trim the first character (as special char) when appending or prepending content

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
> Check that the character to be deleted is a special char

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Added another helper for looking up PRs

- Extensions/XplatGenerateReleaseNotes/V3/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/task.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/GenerateReleaseNotesConsoleTester.ts
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/build-settings.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/release-settings.json
- Extensions/XplatGenerateReleaseNotes/readme.md
> Add a build/release override option to specify the build/release to compare against

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Add batch handling for the PR discovery

- Extensions/XplatGenerateReleaseNotes/V3/task.json
- Extensions/XplatGenerateReleaseNotes/readme.md
> Documentation update

- Extensions/YamlGenerator/YamlGeneratorTask/src/Generate-YAMLDocumentation.ts
> Show the version in the generated sample

- .github/workflows/codeql-analysis.yml
- Extensions/ArtifactDescription/azure-pipelines.yml
- Extensions/BuildUpdating/azure-pipelines.yml
- Extensions/DevTestLab/azure-pipelines-build.yml
- Extensions/FileUtilities/azure-pipelines-build.yml
- Extensions/GenerateReleaseNotes/readme.md
- Extensions/Versioning/VersionDacpacTask/test/File-Processing.tests.ps1
- Extensions/Versioning/VersionDacpacTask/test/Get-Toolpath.tests.ps1
- Extensions/Versioning/VersionPowerShellModule/test/Update-PowerShellModuleVersion.Tests.ps1
- Extensions/Versioning/azure-pipelines-build.yml
- Extensions/WikiPDFExport/azure-pipelines-build.yml
- Extensions/WikiUpdater/azure-pipelines-build.yml
- Extensions/XplatGenerateReleaseNotes/azure-pipelines-build.yml
- Extensions/YamlGenerator/azure-pipelines-build.yml
- README.md
Fixes #852
Mark them off as tested
> A long delayed swapped of the trunk from master to main

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
--GenerateReleaseNotes Node based Cross Platform Task
Ensure current pull request includes label data, so it is consistent with other pull requests retrieved by the call to getPullRequestsByProject
Implements #857
> Populate labels (tags) for current pull request

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Adds code to enrich PRs with extra info for linking items

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Adds enriching the PR with their source commits

- Extensions/XplatGenerateReleaseNotes/V3/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/task.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/GenerateReleaseNotesConsoleTester.ts
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/build-settings.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/release-settings.json
- Extensions/XplatGenerateReleaseNotes/readme.md
> Added a means to get in directly associated PRs

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Adds indirect PRs to the list of available objects in a template 

- Extensions/XplatGenerateReleaseNotes/BuildNotes.md
- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
fixes #765 and provides a simpler implementation for #880
> Add support for old URL format when enriching CS

- Extensions/ArtifactDescription/azure-pipelines.yml
- Extensions/BuildUpdating/azure-pipelines.yml
- Extensions/DevTestLab/azure-pipelines-build.yml
- Extensions/FileUtilities/XmlFileUpdateTask/package-lock.json
- Extensions/FileUtilities/XmlFileUpdateTask/package.json
- Extensions/FileUtilities/XmlFileUpdateTask/src/FileUpdateFunctions.ts
- Extensions/FileUtilities/azure-pipelines-build.yml
- Extensions/Versioning/azure-pipelines-build.yml
- Extensions/WikiPDFExport/azure-pipelines-build.yml
- Extensions/WikiUpdater/azure-pipelines-build.yml
- Extensions/YamlGenerator/azure-pipelines-build.yml
- YAMLTemplates/build-node-task.yml
- YAMLTemplates/publish-extension.yml
Bring all the references to the TFX task used to package the extension to the current version
> Update the various TFX versions

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Added retry logic for all the Azure DevOps REST calls

- Extensions/XplatGenerateReleaseNotes/V3/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/task.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/GenerateReleaseNotesConsoleTester.ts
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/build-settings.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/release-settings.json
- Extensions/XplatGenerateReleaseNotes/readme.md
> Add parameters to control retry logic

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Altered the retry logic to recreates connection to API

- Extensions/XplatGenerateReleaseNotes/V3/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/task.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/GenerateReleaseNotesConsoleTester.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
- Reverted out my bespoke retry logic as it does not work.
- Tried the retry parameters to the MS provided retry settings
- Fixed a batching issue when discovering tests
fixes #648
> Revised retry logic

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Added null check when searching for associated PRs

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Alter catch error handler

- Extensions/XplatGenerateReleaseNotes/V3/package-lock.json
- Extensions/XplatGenerateReleaseNotes/V3/package.json
> Bump version of azure-devops-node-api to 10.2.0

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/package-lock.json
> Added allowCrossOriginAuthentication set to true for token handlers

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
Fixes #934
Other suggestions welcome
> Fix inconsistend ordering for build listing API

- Extensions/BuildUpdating/BuildRetensionTask/src/BuildRetensionTask.ts
- Extensions/BuildUpdating/BuildRetensionTask/task/BuildRetensionTask.ps1
- Extensions/BuildUpdating/BuildVariableTask/package-lock.json
- Extensions/BuildUpdating/BuildVariableTask/src/BuildVariableTask.ts
- Extensions/BuildUpdating/BuildVariableTask/task/BuildVariableTask.ps1
- Extensions/BuildUpdating/GetBuildDefinitionVariableValueTask/package-lock.json
- Extensions/BuildUpdating/GetBuildDefinitionVariableValueTask/src/GetBuildVariableTask.ts
> Add quotes around teamproject name incase it has spaces

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Correct handling for empty customHandlebarsExtensionFile parameter

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Added manual tests to the available options in the test results

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Remove the unnecessary domain check when enriching tfsgit commit comments so on-premise Azure DevOps Service is supported

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/azure-pipelines-build.yml
> Added the option to handle spaces in filenames

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Move the change enrichment it is run for all Classic release code paths

- Extensions/WikiUpdater/WikiFolderUpdaterTask/package-lock.json
- Extensions/WikiUpdater/WikiFolderUpdaterTask/package.json
- Extensions/WikiUpdater/WikiUpdaterTask/package-lock.json
- Extensions/WikiUpdater/WikiUpdaterTask/package.json
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/readme.md
> Add option to insert a new line between appended/prepended content to single file WIKIUpdater task

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/azure-pipelines-build.yml
- Extensions/XplatGenerateReleaseNotes/readme.md
> Add consumed artifacts

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Swap API version to get the consumed artifacts for old versions of API

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/azure-pipelines-build.yml
- Extensions/WikiUpdater/readme.md
> Add the option to create a .order file

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/readme.md
> Revised docmentation and logging

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 3/build-handlebars-template.md
> Added enriched of pipeline `consumedArtifacts` to include commits and wI

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Fix missing currentstage data for first run of a multi-stage YAML pipeline

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 3/build-consumed-artifact-table.md
- Fixes enrichment the code path when consumedartifact is not a pipeline
- Added sample template to list consumedartifacts as a table
Fixes #1035
> Fixes enrichment the code path when consumedartifact is not a pipeline

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- SampleTemplates/XplatGenerateReleaseNotes (Node based)/Version 3/build-consumed-artifact-table.md
> Set the versionName to a range when running in checkstage mode

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Added an extra null check

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Swapped the way absolute paths are detected for the customHandlebarsExtensionFolder parameter

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Fixes push of the found AB#123 format WI Details

- Extensions/XplatGenerateReleaseNotes/V3/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/task.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/GenerateReleaseNotesConsoleTester.ts
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/build-settings.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/release-settings.json
- Extensions/XplatGenerateReleaseNotes/readme.md
> Add the option to force the CS sort order

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Add a null check in case an artifact has no associated WI

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Altered the logging order to make sure nulls are trapped

- Extensions/XplatGenerateReleaseNotes/V3/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/task.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/GenerateReleaseNotesConsoleTester.ts
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/build-settings.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/release-settings.json
- Extensions/XplatGenerateReleaseNotes/pipeline-test-steps.yml
- Extensions/XplatGenerateReleaseNotes/readme.md
> Adds WIQL support

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Revise API calls to get the max WI and CS

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Simplify the calling of the manual WI association

- Extensions/ArtifactDescription/ArtifactDescriptionTask/package-lock.json
- Extensions/ArtifactDescription/ArtifactDescriptionTask/package.json
- Extensions/ArtifactDescription/ArtifactDescriptionTask/task/task.json
- Extensions/BuildUpdating/BuildRetensionTask/task/task.json
- Extensions/BuildUpdating/BuildVariableTask/task/task.json
- Extensions/BuildUpdating/GetBuildDefinitionVariableValueTask/task/task.json
- Extensions/FileUtilities/XmlFileUpdateTask/task/task.json
- Extensions/Versioning/VersionAndroidManifest/task/task.json
- Extensions/Versioning/VersionAngularFileTask/task/task.json
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/task/task.json
- Extensions/Versioning/VersionJSONFileTask/task/task.json
- Extensions/WikiPDFExport/WikiPDFExportTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/YamlGenerator/YamlGeneratorTask/task/task.json
> Update all Node6 based tasks to Node10

- Extensions/WikiPDFExport/WikiPDFExportTask/package-lock.json
- Extensions/WikiPDFExport/WikiPDFExportTask/package.json
- Extensions/WikiPDFExport/WikiPDFExportTask/src/ExportFunctions.ts
- Extensions/WikiPDFExport/WikiPDFExportTask/src/GitWikiFunctions.ts
- Extensions/WikiPDFExport/WikiPDFExportTask/src/WikiPDFExportTask.ts
- Extensions/WikiPDFExport/WikiPDFExportTask/task/task.json
- Extensions/WikiPDFExport/WikiPDFExportTask/test/getExe.test.ts
- Extensions/WikiPDFExport/WikiPDFExportTask/test/testrunnerForSingleFile.ts
- Extensions/WikiPDFExport/WikiPDFExportTask/test/testrunnerForWikiWithNoClone.ts
- Extensions/WikiPDFExport/WikiPDFExportTask/test/testrunnerToCloneFromAzureDevOps.ts
- Extensions/WikiPDFExport/WikiPDFExportTask/test/testrunnerToCloneFromGitHub.ts
- Extensions/WikiPDFExport/azure-pipelines-build.yml
- Extensions/WikiPDFExport/readme.md
- Extensions/WikiPDFExport/test-stage.yml
> Add PDF export crossplatform support

- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
> Update execution engine to Node10

- Extensions/WikiPDFExport/WikiPDFExportTask/src/ExportFunctions.ts
- Extensions/WikiPDFExport/azure-pipelines-build.yml
- Extensions/WikiPDFExport/readme.md
> Add mac support

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/package-lock.json
> Add logic to YAML path

- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
> Added logging to export getLastSuccessfulBuildByStage

- Extensions/YamlGenerator/YamlGeneratorTask/package.json
Set correct name in package.json file so synk.io list is correct
> Set correct name in package.json file

- Extensions/FileUtilities/XmlFileUpdateTask/package-lock.json
- Extensions/FileUtilities/XmlFileUpdateTask/package.json
- Extensions/FileUtilities/XmlFileUpdateTask/src/FileUpdateFunctions.ts
- Extensions/FileUtilities/XmlFileUpdateTask/test/findFileTests.ts
- Extensions/FileUtilities/XmlFileUpdateTask/test/processFileNoRecursionTests.ts
- Extensions/FileUtilities/XmlFileUpdateTask/test/processFileRecursionTests.ts
- Extensions/FileUtilities/XmlFileUpdateTask/test/processFileTests.ts
- Extensions/FileUtilities/XmlFileUpdateTask/test/testdata/lfonly.updated
- Extensions/FileUtilities/XmlFileUpdateTask/test/testdata/lfonly.xml
- Improve the handling of CRLR and LR line endings so they should not be changed if this task is used
- Update packages to address dependabot issues
> Improve the handling of CRLR and LR line endings

- Extensions/XplatGenerateReleaseNotes/V3/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/V3/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/V3/task.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/GenerateReleaseNotesConsoleTester.ts
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/build-settings.json
- Extensions/XplatGenerateReleaseNotes/V3/testconsole/release-settings.json
- Extensions/XplatGenerateReleaseNotes/pipeline-test-steps.yml
- Extensions/XplatGenerateReleaseNotes/readme.md
> Adds skip PR discovery and new Tested By relationship handling 

- Extensions/Versioning/VersionIOSPlistManifest/task/task.json
> Fix group mismatch in manifest of the IOSPlist Versioner

- Extensions/Versioning/VersionDacpacTask/src/Update-DacPacVersionNumber.ps1
- Extensions/Versioning/VersionDacpacTask/src/task.json
- Extensions/Versioning/VersionDacpacTask/test/Get-Toolpath.tests.ps1
- Extensions/Versioning/readme.md
> Rebuilt the DAC assembly discovery logic

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/azure-pipelines-build.yml
- Extensions/WikiUpdater/readme.md
> Adds the option to pass a path to the .order file

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
> Tidy the entry in the order file

- Extensions/WikiUpdater/WikiFolderUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiFolderUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/package-lock.json
- Extensions/WikiUpdater/readme.md
- Extensions/WikiUpdater/vss-extension.json
Currently there is an issue for self-signed local TFS installations:
SSL certificate problem: unable to get local issuer certificate
https://tfs.local.foobar.com/tfs/dev2/Playground/_wiki/wikis/Playground.wiki/': SSL certificate problem: unable to get local issuer certificate
I added a parameter "SslBackend" to optionally send the -c http.sslbackend="schannel" parameter with the git requests.
> Parameter for http.sslbackend="schannel"

- Extensions/WikiUpdater/WikiFolderUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
Fix for PR #1319 (Remove "" on git command)
> Remove " in WikiUpdater whhen using  SSLBackchannel

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/azure-pipelines-build.yml
- Extensions/WikiUpdater/readme.md
> Add the ability to inject a [[_TOC_]] when pre-pending WIKI content

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
> Correct issues when injecting TOC and prepending WIKI pages

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
> Swap to regex for the filter to find TOC block

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
> Add logic to avoid duplicates in entry file

- Extensions/Versioning/VersionDotNetCoreAssembliesTask/src/ApplyVersionToAssemblies.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/src/AppyVersionToAssembliesFunctions.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/task/task.json
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/FileProcessingTest.ts
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/test/FindFilesTests.ts
- Extensions/Versioning/readme.md
> Exposed the list of default field to update

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/task/task.json
> Remove the stray space in the task.json

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/GenerateReleaseNotes.ts
- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/GenerateReleaseNotesConsoleTester.ts
- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/task/task.json
- Extensions/XplatGenerateReleaseNotes/pipeline-test-steps.yml
- Extensions/XplatGenerateReleaseNotes/readme.md
> Add a means to pass in a user defined shared WIQL query to return WI

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/GenerateReleaseNotesConsoleTester.ts
- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts
- Extensions/XplatGenerateReleaseNotes/readme.md
> Expose the published artifacts for a build so they can be used in release notes

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts
> Make sure the publishArtifacts array is initialised as an empty array

- Extensions/ArtifactDescription/azure-pipelines.yml
- Extensions/BuildUpdating/azure-pipelines.yml
- Extensions/DevTestLab/azure-pipelines-build.yml
- Extensions/FileUtilities/azure-pipelines-build.yml
- Extensions/Versioning/azure-pipelines-build.yml
- Extensions/WikiPDFExport/azure-pipelines-build.yml
- Extensions/WikiUpdater/azure-pipelines-build.yml
- Extensions/XplatGenerateReleaseNotes/azure-pipelines-build.yml
- Extensions/YamlGenerator/azure-pipelines-build.yml
- YAMLTemplates/post-publish.yml
Swap from Twitter API 1.0 based task to use a Logic App that can handle API 2.0 OAUTH
> Swap method to send Tweet to use Logic App

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts
> Add an extra call to get the truncated PR description

- Extensions/WikiUpdater/WikiFolderUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiFolderUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/azure-pipelines-build.yml
- Extensions/WikiUpdater/multi-file-test-steps.yml
- Extensions/WikiUpdater/readme.md
- Extensions/WikiUpdater/single-file-test-steps.yml
> Add the option to rebase as opposed to a pull prior to a push if the WIKI updaters need to retry

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/testconsole/readme.md
fix: correct typo in launch.json
--add Extension/Task name--
XplatGenerateReleaseNotesTask/testconsole
--add description--
--add Issue number--
No
> fix: correct typo in xPlatReleaseNotes readme's launch.json inline code

- Extensions/WikiUpdater/WikiUpdaterTask/src/GitWikiTask.ts
> Fixes bug where  buffer is returned as opposed to string in WIKIUpdater

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/GenerateReleaseNotesConsoleTester.ts
- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts
Revises the console tester settings loading to set defaults fixes #1562 
Put a guard on the get parents function the sure there is a parent object before trying to access it fixes #1471
> Various settings related fixes

- Extensions/WikiPDFExport/WikiPDFExportTask/src/ExportFunctions.ts
- Extensions/WikiPDFExport/WikiPDFExportTask/task/task.json
- Extensions/WikiPDFExport/readme.md
- Extensions/WikiPDFExport/test-stage.yml
> Improve the parameter checking and logging in the WIKIPDF exporter

- Extensions/Versioning/VersionDacpacTask/src/Update-DacPacVersionNumber.ps1
> Add retry logic to DacPac versioner

- Extensions/WikiUpdater/WikiFolderUpdaterTask/WikiFolderUpdaterTaskV2/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiFolderUpdaterTask/WikiFolderUpdaterTaskV2/task/task.json
- Extensions/WikiUpdater/WikiFolderUpdaterTask/WikiFolderUpdaterTaskV3/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV2/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV2/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV3/src/GitWikiFuntions.ts
> Fix issue so that Git Config user.name is set correctly

- Extensions/WikiUpdater/WikiFolderUpdaterTask/WikiFolderUpdaterTaskV2/task/task.json
- Extensions/WikiUpdater/WikiFolderUpdaterTask/WikiFolderUpdaterTaskV3/package-lock.json
- Extensions/WikiUpdater/WikiFolderUpdaterTask/WikiFolderUpdaterTaskV3/package.json
- Extensions/WikiUpdater/WikiFolderUpdaterTask/WikiFolderUpdaterTaskV3/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV2/package-lock.json
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV2/package.json
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV2/src/GitWikiFuntions.ts
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV2/src/GitWikiTask.ts
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV2/task/task.json
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV2/test/foldercreation.test.ts
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV2/test/geturl.test.ts
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV2/test/testrunnerToCreateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV2/test/testrunnerToCreateOnGitHub.ts
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV2/test/testrunnerToUpdateOnAzureDevOps.ts
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV3/package-lock.json
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV3/package.json
- Extensions/WikiUpdater/WikiUpdaterTask/WikiUpdaterTaskV3/src/GitWikiFuntions.ts
> Fix regression error in V2 of WIKIUpdater prependEntryToOrderFile setting being ignored

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/task/task.json
> Removed the visability rules that cause an issue with AZDO Server 2020

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts
> Make sure the case of the URL parser filter matches the usage in the current URL

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts
> Add a guard method around the scan for related WI incase there are none

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts
> Added guard check for all calls to relations

- Extensions/ArtifactDescription/azure-pipelines.yml
- Extensions/BuildUpdating/azure-pipelines.yml
- Extensions/DevTestLab/azure-pipelines-build.yml
- Extensions/FileUtilities/azure-pipelines-build.yml
- Extensions/Sarif2JUnitConverter/azure-pipelines-build.yml
- Extensions/Versioning/azure-pipelines-build.yml
- Extensions/WikiPDFExport/azure-pipelines-build.yml
- Extensions/WikiUpdater/azure-pipelines-build.yml
- Extensions/XplatGenerateReleaseNotes/pipeline-test-steps.yml
- Extensions/YamlGenerator/azure-pipelines-build.yml
- YAMLTemplates/post-publish.yml
- YAMLTemplates/publish-extension.yml
Remove the Node10 based Azure Pipeline tasks, direct replacements with newer versions
> Update YAML tasks to current versions

- Extensions/Versioning/VersionDacpacTask/src/Update-DacPacVersionNumber.ps1
- Extensions/Versioning/VersionDacpacTask/src/task.json
- Extensions/Versioning/VersionDacpacTask/test/File-Processing.tests.ps1
- Extensions/Versioning/readme.md
> 1944 it should be possible to explicitly set sqlproj dacversion field instead of relying on search for dacpac files

- Extensions/Versioning/VersionDacpacTask/src/Update-DacPacVersionNumber.ps1
> Move the tool detection so only done if DACPACs found

- Extensions/DevTestLab/StartVM/task.json
- Extensions/DevTestLab/StopVM/task.json
- Extensions/DevTestLab/azure-pipelines-build.yml
- Extensions/DevTestLab/readme.md
> Deprecate the DevLabs task

- Extensions/FileUtilities/XmlFileUpdateTask/task/task.json
- Extensions/FileUtilities/azure-pipelines-build.yml
Adds Node 20 to the executor
fixes #2106
> Add Node 20 support to XMLFileUpdate

- Extensions/Versioning/VersionAndroidManifest/task/task.json
- Extensions/Versioning/VersionAngularFileTask/task/task.json
- Extensions/Versioning/VersionDotNetCoreAssembliesTask/task/task.json
- Extensions/Versioning/VersionIOSPlistManifest/task/task.json
- Extensions/Versioning/VersionJSONFileTask/task/task.json
Adds Node20 execution paths
fixes #2106
> Add Node 20 Support to versioning tasks

- Extensions/XplatGenerateReleaseNotes/XplatGenerateReleaseNotesTask/src/ReleaseNotesFunctions.ts
Generate Release Notes (Node Cross Platform)
Expand truncated commit messages inside consumedArtifacts.
#2119
> Expand consumedArtifacts truncated commit messages.
